package org.igo.mycorc.ui.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import mycorc.composeapp.generated.resources.Res
import mycorc.composeapp.generated.resources.*
import org.igo.mycorc.domain.strings.AppStrings
import org.jetbrains.compose.resources.stringResource

data class AppStringsImpl(
    override val loginTitle: String,
    override val authCardTitle: String,
    override val emailLabel: String,
    override val passwordLabel: String,
    override val loginButton: String,
    override val noAccountText: String,
    override val registerLink: String,
    override val dashboardTitle: String,
    override val syncWithServer: String,
    override val addButtonTooltip: String,
    override val noRecordsMessage: String,
    override val weightLabel: String,
    override val coalLabel: String,
    override val fillAllFieldsWarning: String,
    override val sendToRegistration: String,
    override val sentToRegistration: String,
    override val approved: String,
    override val rejected: String,
    override val readOnlyTitle: String,
    override val editTitle: String,
    override val createNewTitle: String,
    override val biomassWeightLabel: String,
    override val coalWeightLabel: String,
    override val descriptionSection: String,
    override val enterDescription: String,
    override val photoSection: String,
    override val noPhotoPlaceholder: String,
    override val saveChanges: String,
    override val saveNote: String,
    override val photoSaved: String,
    override val cannotEditError: String,
    override val alreadySentError: String,
    override val alreadySentConflictError: String,
    override val settingsTitle: String,
    override val themeSection: String,
    override val systemTheme: String,
    override val lightTheme: String,
    override val darkTheme: String,
    override val languageSection: String,
    override val languageEn: String,
    override val languageRu: String,
    override val languageDe: String,
    override val profileTitle: String,
    override val loggedInAs: String,
    override val loading: String,
    override val logoutButton: String,
    override val packagesNav: String,
    override val facilitiesNav: String,
    override val settingsNav: String,
    override val profileNav: String,
    override val backButtonTooltip: String,
    override val facilitiesSection: String,
    override val sectionBiomass: String,
    override val sectionPyrolysis: String,
    override val sectionBiochar: String,
    override val sectionDelivery: String,
    override val transportDistanceLabel: String,
    override val pyrolysisDurationLabel: String,
    override val pyrolysisTemperatureLabel: String,
) : AppStrings

val LocalAppStrings = compositionLocalOf<AppStrings> {
    error("AppStrings not provided")
}

@Composable
fun rememberAppStrings(languageConfig: org.igo.mycorc.ui.screen.settings.AppLanguageConfig): AppStrings {
    // Локаль устанавливается в UpdateAppLanguage() перед вызовом этой функции
    // languageConfig используется для принудительной рекомпозиции при смене языка

    return AppStringsImpl(
        loginTitle = stringResource(Res.string.login_title),
        authCardTitle = stringResource(Res.string.auth_card_title),
        emailLabel = stringResource(Res.string.email_label),
        passwordLabel = stringResource(Res.string.password_label),
        loginButton = stringResource(Res.string.login_button),
        noAccountText = stringResource(Res.string.no_account_text),
        registerLink = stringResource(Res.string.register_link),
        dashboardTitle = stringResource(Res.string.dashboard_title),
        syncWithServer = stringResource(Res.string.sync_with_server),
        addButtonTooltip = stringResource(Res.string.add_button_tooltip),
        noRecordsMessage = stringResource(Res.string.no_records_message),
        weightLabel = stringResource(Res.string.weight_label),
        coalLabel = stringResource(Res.string.coal_label),
        fillAllFieldsWarning = stringResource(Res.string.fill_all_fields_warning),
        sendToRegistration = stringResource(Res.string.send_to_registration),
        sentToRegistration = stringResource(Res.string.sent_to_registration),
        approved = stringResource(Res.string.approved),
        rejected = stringResource(Res.string.rejected),
        readOnlyTitle = stringResource(Res.string.readonly_title),
        editTitle = stringResource(Res.string.edit_title),
        createNewTitle = stringResource(Res.string.create_new_title),
        biomassWeightLabel = stringResource(Res.string.biomass_weight_label),
        coalWeightLabel = stringResource(Res.string.coal_weight_label),
        descriptionSection = stringResource(Res.string.description_section),
        enterDescription = stringResource(Res.string.enter_description),
        photoSection = stringResource(Res.string.photo_section),
        noPhotoPlaceholder = stringResource(Res.string.no_photo_placeholder),
        saveChanges = stringResource(Res.string.save_changes),
        saveNote = stringResource(Res.string.save_note),
        photoSaved = stringResource(Res.string.photo_saved),
        cannotEditError = stringResource(Res.string.cannot_edit_error),
        alreadySentError = stringResource(Res.string.already_sent_error),
        alreadySentConflictError = stringResource(Res.string.already_sent_conflict_error),
        settingsTitle = stringResource(Res.string.settings_title),
        themeSection = stringResource(Res.string.theme_section),
        systemTheme = stringResource(Res.string.system_theme),
        lightTheme = stringResource(Res.string.light_theme),
        darkTheme = stringResource(Res.string.dark_theme),
        languageSection = stringResource(Res.string.language_section),
        languageEn = stringResource(Res.string.language_en),
        languageRu = stringResource(Res.string.language_ru),
        languageDe = stringResource(Res.string.language_de),
        profileTitle = stringResource(Res.string.profile_title),
        loggedInAs = stringResource(Res.string.logged_in_as),
        loading = stringResource(Res.string.loading),
        logoutButton = stringResource(Res.string.logout_button),
        packagesNav = stringResource(Res.string.packages_nav),
        facilitiesNav = stringResource(Res.string.facilities_nav),
        settingsNav = stringResource(Res.string.settings_nav),
        profileNav = stringResource(Res.string.profile_nav),
        backButtonTooltip = stringResource(Res.string.back_button_tooltip),
        facilitiesSection = stringResource(Res.string.facilities_section),
        sectionBiomass = stringResource(Res.string.section_biomass),
        sectionPyrolysis = stringResource(Res.string.section_pyrolysis),
        sectionBiochar = stringResource(Res.string.section_biochar),
        sectionDelivery = stringResource(Res.string.section_delivery),
        transportDistanceLabel = stringResource(Res.string.transport_distance_label),
        pyrolysisDurationLabel = stringResource(Res.string.pyrolysis_duration_label),
        pyrolysisTemperatureLabel = stringResource(Res.string.pyrolysis_temperature_label),
    )
}
